theme: jekyll-theme-leap-day
title: Saia da Matrix
description: Site que reúne as mídias sociais do Canal Saia da Matrix. Aqui temos as plataformas para apoiar e ajudar a manter o Canal reunidas de forma prática. Temos os links para o PodCast do Canal bem como para acompanhar todas as redes sociais do Saia da Matrix.
